export class IntentConfig {
  static INTENT_PATTERNS = {
    ACCIDENT_INCIDENT: {
      keywords: [
        'injured',
        'accident',
        'hurt',
        'hospital',
        'sick',
        'fever',
        'fainted',
        'emergency',
        'medical',
        'fell',
        'bleeding',
      ],
      weight: 1.0,
    },
    LOST_FOUND: {
      keywords: ['lost', 'found', 'missing', 'anyone lost', 'looking for'],
      weight: 0.8,
    },
    PICNIC_EXCURSION: {
      keywords: [
        'picnic',
        'excursion',
        'field trip',
        'trip',
        'visit',
        'permission slip',
        'educational trip',
      ],
      weight: 0.9,
    },
    SPORTS_ACTIVITY: {
      keywords: [
        'sports',
        'practice',
        'match',
        'game',
        'football',
        'basketball',
        'tournament',
        'competition',
        'athletic',
      ],
      weight: 0.8,
    },
    EVENT_ANNOUNCEMENT: {
      keywords: [
        'event',
        'meeting',
        'assembly',
        'function',
        'program',
        'concert',
        'workshop',
        'seminar',
        'celebration',
        'ceremony',
        'pta',
        'parent-teacher',
        'annual',
        'cultural',
      ],
      weight: 0.7,
    },
    ASSISTANCE_REQUEST: {
      keywords: [
        'help',
        'assist',
        'volunteer',
        'need',
        'can anyone',
        'who can',
        'looking for',
        'anyone available',
        'support',
      ],
      weight: 0.9,
    },
    DEADLINE_TASKS: {
      keywords: [
        'deadline',
        'due',
        'submit',
        'by',
        'before',
        'reminder',
        'must',
        'should',
        'need to',
        'required',
        'bring',
        'return',
        'fill',
        'complete',
        'sign',
        'send',
        'inform',
        'please',
        'kindly',
      ],
      weight: 0.9,
    },
  };

  static POSITIVE_WORDS = [
    'thanks',
    'thank you',
    'great',
    'good',
    'excellent',
    'wonderful',
    'appreciate',
    'grateful',
    'happy',
    'glad',
  ];

  static NEGATIVE_WORDS = [
    'urgent',
    'emergency',
    'problem',
    'issue',
    'concern',
    'worried',
    'unfortunately',
    'sorry',
    'cancel',
    'postpone',
  ];

  static HIGH_URGENCY = [
    'urgent',
    'emergency',
    'immediately',
    'asap',
    'critical',
    'injured',
    'accident',
    'hospital',
  ];

  static MEDIUM_URGENCY = [
    'important',
    'soon',
    'today',
    'deadline',
    'reminder',
    'tomorrow',
    'need',
    'required',
    'volunteers needed',
  ];

  static EVENT_KEYWORDS = [
    'event',
    'meeting',
    'assembly',
    'function',
    'program',
    'concert',
    'workshop',
    'seminar',
    'celebration',
    'ceremony',
    'practice',
    'rehearsal',
    'picnic',
    'excursion',
    'trip',
    'sports day',
    'annual day',
    'cultural program',
    'parent-teacher meeting',
    'pta meeting',
    'fair',
    'competition',
    'tournament',
    'match',
  ];

  static ASSISTANCE_KEYWORDS = [
    'help',
    'assist',
    'volunteer',
    'need',
    'can anyone',
    'who can',
    'looking for',
    'support',
    'participate',
    'anyone available',
    'able to',
    'willing to',
  ];

  static DEADLINE_KEYWORDS = [
    'deadline',
    'due',
    'submit',
    'by',
    'before',
    'reminder',
    'must',
    'should',
    'need to',
    'required',
    'bring',
    'return',
    'fill',
    'complete',
    'sign',
    'send',
    'inform',
    'please',
    'kindly',
  ];

  static ASSIGNMENT_RULES: Record<string, string[]> = {
    ACCIDENT_INCIDENT: ['Admin', 'School Nurse', 'Principal'],
    LOST_FOUND: ['Class Teacher'],
    PICNIC_EXCURSION: ['Event Coordinator', 'Admin'],
    SPORTS_ACTIVITY: ['Sports Teacher'],
    EVENT_ANNOUNCEMENT: ['Admin', 'Event Coordinator'],
    ASSISTANCE_REQUEST: ['Event Coordinator', 'Volunteer Coordinator'],
    DEADLINE_TASKS: ['Class Teacher', 'Admin'],
  };

  static GENERAL_INFO_PATTERNS: RegExp[] = [
    /^(ok|okay|k|yes|no|noted|thanks|thank you)$/i,
    /^good (morning|afternoon|evening|night)$/i,
    /^(lol|haha)$/i,
    /^(will do|got it|sure|alright)$/i,
  ];

  static INTENT_PROTOTYPES: Record<string, string[]> = {
    ACCIDENT_INCIDENT: ['student injured or medical emergency'],
    LOST_FOUND: ['lost or found item at school'],
    PICNIC_EXCURSION: ['school excursion, field trip or picnic'],
    SPORTS_ACTIVITY: ['sports practice, game, or tournament'],
    EVENT_ANNOUNCEMENT: ['school event or meeting announcement'],
    ASSISTANCE_REQUEST: ['requesting help or volunteers'],
    DEADLINE_TASKS: ['deadline or submission required'],
  };
}
